
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 54
#define YY_END_OF_BUFFER 55
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_acclist[489] =
    {   0,
       39,   39,   50,   50,   55,   53,   54,   52,   53,   54,
       51,   52,   54,   33,   53,   54,   47,   53,   54,   33,
       53,   54,   53,   54,   33,   53,   54,   39,   53,   54,
       39,   53,   54,   33,   53,   54,   33,   53,   54,   33,
       53,   54,   36,   53,   54,16421,   36,   53,   54,16421,
       36,   53,   54,16421,   36,   53,   54,16421,   29,   33,
       53,   54,   36,   53,   54,16421,   36,   53,   54,16421,
       36,   53,   54,16421,   36,   53,   54,16421,   36,   53,
       54,16421,   36,   53,   54,16421,   36,   53,   54,16421,
       36,   53,   54,16421,   36,   53,   54,16421,   36,   53,

       54,16421,   36,   53,   54,16421,   36,   53,   54,16421,
       53,   54,   42,   54,   41,   54,   46,   54,   45,   54,
       46,   54,   50,   54,   48,   54,   49,   54,   54,   31,
       54,   30,   31,   54,   32,   54,   26,   27,   43,   40,
       38,   39,   24,   23,   25,   36,16421,   36, 8229,16421,
       36, 8229,16421,   36, 8229,16421,   36, 8229,16421,   36,
     8229,16421,   36, 8229,16421,   36, 8229,16421,   36, 8229,
    16421,   36, 8229,16421,   36, 8229,16421,   36, 8229,16421,
       36, 8229,16421,   14,   36, 8229,16421,   36, 8229,16421,
       36, 8229,16421,   36, 8229,16421,   36, 8229,16421,   36,

     8229,16421,   36, 8229,16421,   36, 8229,16421,   36, 8229,
    16421,   36, 8229,16421,   28,   44,   50,   38,   39, 8229,
       36, 8229,16421,   36, 8229,16421,   18,   36, 8229,16421,
       36, 8229,16421,   36, 8229,16421,   36, 8229,16421,   36,
     8229,16421,   36, 8229,16421,   36, 8229,16421,   36, 8229,
    16421,   36, 8229,16421,   36, 8229,16421,   12,   36, 8229,
    16421,   36, 8229,16421,    2,   36, 8229,16421,   36, 8229,
    16421,   36, 8229,16421,   36, 8229,16421,   36, 8229,16421,
       36, 8229,16421,   36, 8229,16421,   36, 8229,16421,   38,
     8229,   36, 8229,16421,   36, 8229,16421,   36, 8229,16421,

        4,   36, 8229,16421,   36, 8229,16421,   36, 8229,16421,
       36, 8229,16421,   15,   36, 8229,16421,   36, 8229,16421,
       36, 8229,16421,   36, 8229,16421,   36, 8229,16421,    8,
       36, 8229,16421,   36, 8229,16421,   36, 8229,16421,    9,
       36, 8229,16421,   34,   36, 8229,16421,    1,   36, 8229,
    16421,   36, 8229,16421,   36, 8229,16421,   20,   36, 8229,
    16421,   36, 8229,16421,   36, 8229,16421,   17,   36, 8229,
    16421,    6,   36, 8229,16421,   36, 8229,16421,   36, 8229,
    16421,   35,   36, 8229,16421,   36, 8229,16421,   36, 8229,
    16421,   36, 8229,16421,   36, 8229,16421,   13,   36, 8229,

    16421,   36, 8229,16421,   36, 8229,16421,   36, 8229,16421,
        3,   36, 8229,16421,   36, 8229,16421,   36, 8229,16421,
       36, 8229,16421,   16,   36, 8229,16421,    5,   36, 8229,
    16421,   36, 8229,16421,   36, 8229,16421,   36, 8229,16421,
       10,   36, 8229,16421,   36, 8229,16421,   36, 8229,16421,
       19,   36, 8229,16421,   36, 8229,16421,   22,   36, 8229,
    16421,   36, 8229,16421,   36, 8229,16421,   36, 8229,16421,
       36, 8229,16421,    7,   36, 8229,16421,   36, 8229,16421,
       11,   36, 8229,16421,   21,   36, 8229,16421
    } ;

static yyconst flex_int16_t yy_accept[182] =
    {   0,
        1,    2,    3,    3,    3,    3,    3,    4,    5,    5,
        5,    6,    8,   11,   14,   17,   20,   23,   25,   28,
       31,   34,   37,   40,   43,   47,   51,   55,   59,   63,
       67,   71,   75,   79,   83,   87,   91,   95,   99,  103,
      107,  111,  113,  115,  117,  119,  121,  123,  125,  127,
      129,  130,  132,  135,  137,  138,  139,  140,  141,  142,
      143,  143,  144,  145,  146,  146,  148,  151,  154,  157,
      160,  163,  166,  169,  172,  175,  178,  181,  184,  188,
      191,  194,  197,  200,  203,  206,  209,  212,  215,  216,
      217,  218,  219,  219,  220,  221,  224,  227,  231,  234,

      237,  240,  243,  246,  249,  252,  255,  258,  262,  265,
      269,  272,  275,  278,  281,  284,  287,  290,  290,  291,
      292,  295,  298,  301,  305,  308,  311,  314,  318,  321,
      324,  327,  330,  334,  337,  340,  344,  348,  352,  355,
      358,  362,  365,  368,  372,  376,  379,  382,  386,  389,
      392,  395,  398,  402,  405,  408,  411,  415,  418,  421,
      424,  428,  432,  435,  438,  441,  445,  448,  451,  455,
      458,  462,  465,  468,  471,  474,  478,  481,  485,  489,
      489
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    1,    6,
        6,    8,    9,    6,    6,   10,   11,   12,   13,   13,
       13,   13,   13,   13,   13,   13,   13,    1,    6,   14,
       15,   16,    1,    1,   17,   18,   18,   18,   19,   18,
       20,   20,   21,   20,   20,   22,   20,   23,   20,   24,
       20,   25,   20,   20,   20,   20,   20,   26,   20,   20,
       27,    6,   28,    1,   29,    1,   30,   31,   32,   33,

       34,   35,   36,   37,   38,   20,   39,   40,   41,   42,
       43,   44,   20,   45,   46,   47,   48,   49,   50,   51,
       52,   20,    6,   53,    6,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[54] =
    {   0,
        1,    2,    3,    1,    4,    1,    1,    1,    1,    1,
        1,    5,    5,    1,    1,    1,    6,    6,    6,    7,
        7,    7,    7,    7,    7,    7,    1,    1,    8,    6,
        6,    6,    6,    6,    6,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    1
    } ;

static yyconst flex_int16_t yy_base[191] =
    {   0,
        0,    0,  121,  111,   51,   52,   53,   58,   62,   64,
      104, 1115, 1115, 1115,   80, 1115, 1115,   84,   60,   60,
       64,   70,   65,   54,   76,   81,   94,   96, 1115,  100,
      115,  119,  134,  138,  184,  117,  119,   40,  134,  147,
      157,    9, 1115, 1115, 1115, 1115,   46,    0, 1115, 1115,
     1115, 1115, 1115, 1115, 1115, 1115, 1115, 1115,  188,  160,
        0, 1115, 1115, 1115,   98,  142,  202,  208,  215,  221,
      227,  233,  252,  266,  271,  273,  286,  294,  306,  309,
      328,  330,  334,  342,  348,  366,  370,  388, 1115, 1115,
        0,  384,  107,    0,    0,  403,  407,  410,  422,  428,

      440,  442,  446,  464,  471,  484,  486,  499,  504,  507,
      522,  527,  535,  540,  547,  555,  577,  121,  144,    0,
      580,  592,  598,  595,  620,  600,  628,  632,  635,  640,
      653,  660,  668,  673,  681,  688,  696,  701,  709,  724,
      729,  732,  737,  744,  752,  765,  777,  780,  783,  785,
      805,  813,  819,  825,  827,  833,  848,  855,  868,  870,
      876,  883,  891,  904,  906,  912,  919,  924,  942,  947,
      955,  960,  962,  975,  990,  998, 1003, 1010, 1018, 1115,
     1048, 1056, 1064, 1072, 1079, 1087, 1091, 1096, 1102, 1106
    } ;

static yyconst flex_int16_t yy_def[191] =
    {   0,
      180,    1,  181,  181,  182,  182,  183,  183,  184,  184,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  185,  185,  185,  185,  180,  185,
      185,  185,  185,  185,  185,   35,   35,   35,   35,   35,
       35,  180,  180,  180,  180,  180,  180,  186,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      187,  180,  180,  180,  188,   35,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  180,  180,
      186,  180,  180,  187,  190,  189,  189,  189,  189,  189,

      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  180,  180,  190,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,    0,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180
    } ;

static yyconst flex_int16_t yy_nxt[1169] =
    {   0,
       12,   13,   14,   15,   16,   17,   18,   17,   17,   17,
       19,   20,   21,   22,   23,   24,   25,   25,   25,   25,
       25,   25,   26,   27,   28,   25,   29,   17,   12,   25,
       30,   31,   32,   33,   34,   25,   25,   35,   25,   25,
       25,   36,   25,   25,   37,   38,   39,   25,   40,   41,
       25,   25,   42,   46,   46,   49,   90,   50,   47,   47,
       49,   89,   50,   52,   53,   52,   53,   57,   64,   59,
       58,   60,   60,   59,   67,   60,   60,   65,   65,   63,
       67,   67,   65,   65,   62,   61,   84,   66,   66,   54,
       56,   54,   66,   66,   55,   65,   65,   65,   65,   65,

       65,   65,   65,  180,   66,   66,   66,   66,   66,   66,
       61,   66,   66,   44,   68,  118,   65,   65,  119,  119,
       65,   65,   66,   44,   66,  180,   66,   66,   66,   70,
       66,   66,  119,  119,  180,   65,   65,  180,   69,   65,
       65,  180,   71,   66,   72,   66,   66,   66,  180,   66,
       66,   67,   83,   67,   73,  119,  119,   67,   67,   67,
       67,   74,   66,  180,   82,  180,   66,   77,   67,   59,
       85,   60,   60,   75,   67,   67,   67,  180,   86,  180,
       78,   67,   67,   67,   76,   65,   65,   67,   67,   87,
      180,   67,  180,   88,  180,   66,   66,   67,   67,   92,

       92,  180,  180,   65,   65,  180,   93,  180,  180,   65,
       65,  180,   66,   96,   96,  180,   65,   65,   79,   96,
       96,   93,   65,   65,   80,   81,   96,   96,   65,   65,
       96,  180,   96,   96,   65,   65,   96,  180,   96,   96,
       93,  180,  180,   96,   96,   96,  180,  180,  180,   96,
      100,  180,   99,   65,   65,   96,  180,   98,  180,  180,
      180,   96,  180,   96,   96,  180,  102,   65,   65,  101,
      180,  180,   65,   65,   65,   65,  180,   96,   96,  180,
       96,  103,   96,   96,   96,   96,  180,   65,   65,  180,
      180,  180,  180,  180,   96,   65,   65,   96,   96,   96,

      180,   96,  180,  180,  180,   96,   96,   65,   65,  180,
       65,   65,  180,  104,   96,  180,  105,   96,   96,  106,
       96,   96,   96,  180,  180,  107,  180,  180,  180,   65,
       65,   65,   65,  180,   96,   65,   65,   96,  108,   96,
       96,   96,   96,   65,   65,   96,   96,  180,  180,   65,
       65,  180,  109,   96,   96,  180,   96,  180,   96,   96,
       96,  180,   96,  180,  180,  180,  180,   65,   65,  111,
       96,   65,   65,  180,  110,  180,   96,   96,   96,  180,
      112,   96,   96,  180,  180,  114,  113,  180,  180,   65,
       65,  180,  180,  180,   96,   92,   92,  180,   96,   96,

       96,  180,   93,  180,   65,   65,  180,  116,   65,   65,
      180,   65,   65,  115,   96,   96,   96,   93,   96,   96,
      180,   96,   96,   65,   65,  117,  121,  180,  180,   65,
       65,   96,  180,   96,   96,   96,   93,  180,   96,   96,
       96,   65,   65,   65,   65,  180,  180,   65,   65,  180,
       96,   96,   96,   96,   96,  180,   96,   96,   96,  180,
      123,  180,  180,  122,  180,   65,   65,  180,   96,  180,
       96,  125,   65,   65,   96,   96,   96,  180,  180,  124,
      180,  180,   96,   96,  180,   65,   65,   65,   65,  180,
      180,  126,   96,  180,  127,   96,   96,   96,   96,   96,

       65,   65,  180,  180,  128,   65,   65,  180,   65,   65,
       96,   96,   96,  180,   96,   96,   96,  129,   96,   96,
      180,  180,  180,   65,   65,  180,  180,   96,   65,   65,
      180,  130,   96,   96,   96,   96,   65,   65,   96,   96,
      132,   65,   65,  131,  180,  180,   96,   96,   65,   65,
       96,   96,   96,  180,  180,   96,   65,   65,   96,   96,
      180,  133,  180,   96,  180,  180,   96,   96,   96,  180,
      180,  180,  135,  180,  134,   96,  180,  180,   65,   65,
      137,   65,   65,   96,  180,  136,  180,  138,   96,   96,
      180,   96,   96,   65,   65,  180,   65,   65,  180,   65,

       65,   65,   65,   96,   96,   96,   96,   96,   96,   96,
       96,   96,   96,  180,  180,  180,  139,  180,  142,  143,
       96,   65,   65,   96,  140,  180,   96,  180,   96,   65,
       65,   96,   96,   65,   65,  180,   65,   65,  141,   96,
       96,   65,   65,   96,   96,  145,   96,   96,   96,  180,
      180,   96,   96,  180,   65,   65,   96,  180,  144,  180,
       96,   65,   65,   96,   96,   96,  180,  146,   96,   65,
       65,   96,   96,  148,   65,   65,  147,  180,  180,   96,
       96,   96,   65,   65,   96,   96,  149,  180,   96,   65,
       65,  180,   96,   96,  180,  180,   96,   65,   65,   96,

       96,   96,   65,   65,  150,  180,  180,   96,   96,   96,
       65,   65,   96,   96,  180,  180,   96,  151,  180,  180,
       96,   96,  152,  180,   96,   65,   65,  180,  180,   96,
       65,   65,  180,   65,   65,   96,   96,   96,   65,   65,
       96,   96,  153,   96,   96,   65,   65,  180,   96,   96,
      180,  180,   96,   65,   65,   96,   96,   96,  180,  180,
       96,  180,  180,   96,   96,   96,   65,   65,  154,  180,
      180,  180,   96,  155,  156,  180,   96,   96,   65,   65,
       96,   65,   65,  180,   65,   65,   65,   65,   96,   96,
      180,   96,   96,   96,   96,   96,   96,   96,  157,  180,

      180,  180,  180,  180,  180,   96,   65,   65,   96,  158,
      180,   96,  180,   96,   65,   65,   96,   96,  180,  160,
       65,   65,  180,  159,   96,   96,   65,   65,   65,   65,
       96,   96,  180,   96,   65,   65,   96,   96,   96,   96,
      180,   96,  180,  180,   96,   96,  161,   96,  162,   65,
       65,  180,  180,   96,  163,   96,   65,   65,  180,   96,
       96,   96,  180,  180,  180,  180,   96,   96,  180,   65,
       65,   65,   65,  164,  165,  180,   96,   65,   65,   96,
       96,   96,   96,   96,   65,   65,  180,   96,   96,  180,
      180,  180,   65,   65,   96,   96,   96,  180,   96,  168,

      166,  167,   96,   96,   96,   65,   65,   65,   65,  180,
      180,   96,  180,   65,   65,   96,   96,   96,   96,   96,
       65,   65,  180,   96,   96,   65,   65,  180,  180,  180,
       96,   96,   96,  180,   96,   96,   96,  170,  180,  171,
       96,  180,  169,   65,   65,  180,  180,   96,   65,   65,
      180,  180,   96,   96,   96,  173,   65,   65,   96,   96,
      172,   65,   65,   65,   65,  180,   96,   96,  180,  180,
       96,   96,   96,   96,   96,   96,   65,   65,  180,  180,
      180,  180,  174,   96,  180,  180,   96,   96,   96,  180,
       96,   65,   65,  180,  180,  176,  180,  180,  180,   65,

       65,   96,   96,   96,   65,   65,  175,  180,  177,   96,
       96,   65,   65,  180,   96,   96,  180,  180,   96,   65,
       65,   96,   96,  180,  180,  180,   96,  180,  180,   96,
       96,   96,  180,  180,  180,  178,  180,  180,   96,  180,
      180,  180,  180,  180,  180,  180,   96,  179,   43,   43,
       43,   43,   43,   43,   43,   43,   45,   45,   45,   45,
       45,   45,   45,   45,   48,   48,   48,   48,   48,   48,
       48,   48,   51,   51,   51,   51,   51,   51,   51,   51,
       67,   67,  180,   67,   67,   67,   67,   91,   91,  180,
      180,   91,   91,   91,   91,   94,   94,   95,   95,  180,

      180,   95,   95,   97,   97,  180,   97,   97,   97,   97,
      120,  120,  120,  120,   11,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180
    } ;

static yyconst flex_int16_t yy_chk[1169] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    5,    6,    7,   47,    7,    5,    6,
        8,   42,    8,    9,    9,   10,   10,   19,   24,   20,
       19,   20,   20,   21,   38,   21,   21,   25,   25,   23,
       38,   38,   26,   26,   22,   20,   38,   25,   25,    9,
       18,   10,   26,   26,   15,   27,   27,   28,   28,   65,

       65,   30,   30,   11,   25,   27,   27,   28,   28,   26,
       20,   30,   30,    4,   26,   93,   31,   31,   93,   93,
       32,   32,   27,    3,   28,    0,   31,   31,   30,   28,
       32,   32,  118,  118,    0,   33,   33,    0,   27,   34,
       34,    0,   30,   31,   30,   33,   33,   32,    0,   34,
       34,   36,   37,   37,   31,  119,  119,   36,   36,   37,
       37,   32,   33,    0,   36,    0,   34,   34,   39,   60,
       39,   60,   60,   33,   39,   39,   66,    0,   39,    0,
       34,   40,   66,   66,   33,   35,   35,   40,   40,   40,
        0,   41,    0,   41,    0,   35,   35,   41,   41,   59,

       59,    0,    0,   67,   67,    0,   59,    0,    0,   68,
       68,    0,   35,   67,   67,    0,   69,   69,   35,   68,
       68,   59,   70,   70,   35,   35,   69,   69,   71,   71,
       67,    0,   70,   70,   72,   72,   68,    0,   71,   71,
       59,    0,    0,   69,   72,   72,    0,    0,    0,   70,
       70,    0,   69,   73,   73,   71,    0,   68,    0,    0,
        0,   72,    0,   73,   73,    0,   72,   74,   74,   71,
        0,    0,   75,   75,   76,   76,    0,   74,   74,    0,
       73,   73,   75,   75,   76,   76,    0,   77,   77,    0,
        0,    0,    0,    0,   74,   78,   78,   77,   77,   75,

        0,   76,    0,    0,    0,   78,   78,   79,   79,    0,
       80,   80,    0,   74,   77,    0,   75,   79,   79,   76,
       80,   80,   78,    0,    0,   77,    0,    0,    0,   81,
       81,   82,   82,    0,   79,   83,   83,   80,   78,   81,
       81,   82,   82,   84,   84,   83,   83,    0,    0,   85,
       85,    0,   80,   84,   84,    0,   81,    0,   82,   85,
       85,    0,   83,    0,    0,    0,    0,   86,   86,   82,
       84,   87,   87,    0,   81,    0,   85,   86,   86,    0,
       83,   87,   87,    0,    0,   85,   84,    0,    0,   88,
       88,    0,    0,    0,   86,   92,   92,    0,   87,   88,

       88,    0,   92,    0,   96,   96,    0,   87,   97,   97,
        0,   98,   98,   86,   96,   96,   88,   92,   97,   97,
        0,   98,   98,   99,   99,   88,   98,    0,    0,  100,
      100,   96,    0,   99,   99,   97,   92,    0,   98,  100,
      100,  101,  101,  102,  102,    0,    0,  103,  103,    0,
       99,  101,  101,  102,  102,    0,  100,  103,  103,    0,
      100,    0,    0,   99,    0,  104,  104,    0,  101,    0,
      102,  102,  105,  105,  103,  104,  104,    0,    0,  101,
        0,    0,  105,  105,    0,  106,  106,  107,  107,    0,
        0,  103,  104,    0,  104,  106,  106,  107,  107,  105,

      108,  108,    0,    0,  105,  109,  109,    0,  110,  110,
      108,  108,  106,    0,  107,  109,  109,  106,  110,  110,
        0,    0,    0,  111,  111,    0,    0,  108,  112,  112,
        0,  107,  109,  111,  111,  110,  113,  113,  112,  112,
      110,  114,  114,  109,    0,    0,  113,  113,  115,  115,
      111,  114,  114,    0,    0,  112,  116,  116,  115,  115,
        0,  111,    0,  113,    0,    0,  116,  116,  114,    0,
        0,    0,  113,    0,  112,  115,    0,    0,  117,  117,
      115,  121,  121,  116,    0,  114,    0,  116,  117,  117,
        0,  121,  121,  122,  122,    0,  124,  124,    0,  123,

      123,  126,  126,  122,  122,  117,  124,  124,  121,  123,
      123,  126,  126,    0,    0,    0,  117,    0,  123,  123,
      122,  125,  125,  124,  121,    0,  123,    0,  126,  127,
      127,  125,  125,  128,  128,    0,  129,  129,  122,  127,
      127,  130,  130,  128,  128,  126,  129,  129,  125,    0,
        0,  130,  130,    0,  131,  131,  127,    0,  125,    0,
      128,  132,  132,  129,  131,  131,    0,  127,  130,  133,
      133,  132,  132,  130,  134,  134,  129,    0,    0,  133,
      133,  131,  135,  135,  134,  134,  131,    0,  132,  136,
      136,    0,  135,  135,    0,    0,  133,  137,  137,  136,

      136,  134,  138,  138,  132,    0,    0,  137,  137,  135,
      139,  139,  138,  138,    0,    0,  136,  134,    0,    0,
      139,  139,  135,    0,  137,  140,  140,    0,    0,  138,
      141,  141,    0,  142,  142,  140,  140,  139,  143,  143,
      141,  141,  139,  142,  142,  144,  144,    0,  143,  143,
        0,    0,  140,  145,  145,  144,  144,  141,    0,    0,
      142,    0,    0,  145,  145,  143,  146,  146,  140,    0,
        0,    0,  144,  142,  143,    0,  146,  146,  147,  147,
      145,  148,  148,    0,  149,  149,  150,  150,  147,  147,
        0,  148,  148,  146,  149,  149,  150,  150,  146,    0,

        0,    0,    0,    0,    0,  147,  151,  151,  148,  147,
        0,  149,    0,  150,  152,  152,  151,  151,    0,  150,
      153,  153,    0,  149,  152,  152,  154,  154,  155,  155,
      153,  153,    0,  151,  156,  156,  154,  154,  155,  155,
        0,  152,    0,    0,  156,  156,  151,  153,  152,  157,
      157,    0,    0,  154,  154,  155,  158,  158,    0,  157,
      157,  156,    0,    0,    0,    0,  158,  158,    0,  159,
      159,  160,  160,  155,  156,    0,  157,  161,  161,  159,
      159,  160,  160,  158,  162,  162,    0,  161,  161,    0,
        0,    0,  163,  163,  162,  162,  159,    0,  160,  160,

      158,  159,  163,  163,  161,  164,  164,  165,  165,    0,
        0,  162,    0,  166,  166,  164,  164,  165,  165,  163,
      167,  167,    0,  166,  166,  168,  168,    0,    0,    0,
      167,  167,  164,    0,  165,  168,  168,  164,    0,  165,
      166,    0,  163,  169,  169,    0,    0,  167,  170,  170,
        0,    0,  168,  169,  169,  168,  171,  171,  170,  170,
      167,  172,  172,  173,  173,    0,  171,  171,    0,    0,
      169,  172,  172,  173,  173,  170,  174,  174,    0,    0,
        0,    0,  170,  171,    0,    0,  174,  174,  172,    0,
      173,  175,  175,    0,    0,  173,    0,    0,    0,  176,

      176,  175,  175,  174,  177,  177,  172,    0,  174,  176,
      176,  178,  178,    0,  177,  177,    0,    0,  175,  179,
      179,  178,  178,    0,    0,    0,  176,    0,    0,  179,
      179,  177,    0,    0,    0,  175,    0,    0,  178,    0,
        0,    0,    0,    0,    0,    0,  179,  177,  181,  181,
      181,  181,  181,  181,  181,  181,  182,  182,  182,  182,
      182,  182,  182,  182,  183,  183,  183,  183,  183,  183,
      183,  183,  184,  184,  184,  184,  184,  184,  184,  184,
      185,  185,    0,  185,  185,  185,  185,  186,  186,    0,
        0,  186,  186,  186,  186,  187,  187,  188,  188,    0,

        0,  188,  188,  189,  189,    0,  189,  189,  189,  189,
      190,  190,  190,  190,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180
    } ;

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
(yy_lp) = (yy_full_lp); /* restore orig. accepting pos. */ \
(yy_state_ptr) = (yy_full_state); /* restore orig. state */ \
yy_current_state = *(yy_state_ptr); /* restore curr. state */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "decaf.l"
#line 5 "decaf.l"
#include "token.h"
std::string string_content;
int start_line;
int retcon = 0;
int bracket_start;




#line 848 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1
#define MULTILINECOMMENT 2
#define STRING 3
#define ARRAY 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 22 "decaf.l"

#line 1034 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 181 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1115 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     (yy_looking_for_trail_begin) )
					{
					if ( yy_act == (yy_looking_for_trail_begin) )
						{
						(yy_looking_for_trail_begin) = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					(yy_looking_for_trail_begin) = yy_act & ~YY_TRAILING_MASK;
					(yy_looking_for_trail_begin) |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					(yy_full_match) = yy_cp;
					(yy_full_state) = (yy_state_ptr);
					(yy_full_lp) = (yy_lp);
					break;
					}
				++(yy_lp);
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 23 "decaf.l"
{return make_token(T_VOID, current_line);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 24 "decaf.l"
{return make_token(T_INT, current_line);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 25 "decaf.l"
{return make_token(T_DOUBLE, current_line);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 26 "decaf.l"
{return make_token(T_BOOL, current_line);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 27 "decaf.l"
{return make_token(T_STRING, current_line);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 28 "decaf.l"
{return make_token(T_CLASS, current_line);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 29 "decaf.l"
{return make_token(T_INTERFACE, current_line);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 30 "decaf.l"
{return make_token(T_NULL, current_line);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 31 "decaf.l"
{return make_token(T_THIS, current_line);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 32 "decaf.l"
{return make_token(T_EXTENDS, current_line);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 33 "decaf.l"
{return make_token(T_IMPLEMENTS, current_line);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 34 "decaf.l"
{return make_token(T_FOR, current_line);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 35 "decaf.l"
{return make_token(T_WHILE, current_line);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 36 "decaf.l"
{return make_token(T_IF, current_line);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 37 "decaf.l"
{return make_token(T_ELSE, current_line);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 38 "decaf.l"
{return make_token(T_RETURN, current_line);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 39 "decaf.l"
{return make_token(T_BREAK, current_line);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 40 "decaf.l"
{return make_token(T_NEW, current_line);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 41 "decaf.l"
{return make_token(T_NEWARRAY, current_line);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 42 "decaf.l"
{return make_token(T_PRINT, current_line);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 43 "decaf.l"
{return make_token(T_READINTEGER, current_line);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 44 "decaf.l"
{return make_token(T_READLINE, current_line);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 46 "decaf.l"
{ return make_token(T_EQ, current_line); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 47 "decaf.l"
{ return make_token(T_LE, current_line); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 48 "decaf.l"
{ return make_token(T_GE, current_line); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 49 "decaf.l"
{ return make_token(T_NEQ, current_line); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 50 "decaf.l"
{ return make_token(T_AND, current_line); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 51 "decaf.l"
{ return make_token(T_OR, current_line); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 53 "decaf.l"
{BEGIN(ARRAY);
    start_line = current_line;}
	YY_BREAK
case 30:
/* rule 30 can match eol */
YY_RULE_SETUP
#line 55 "decaf.l"
{current_line++;}
	YY_BREAK
case 31:
/* rule 31 can match eol */
YY_RULE_SETUP
#line 56 "decaf.l"
{}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 57 "decaf.l"
{BEGIN(INITIAL); return make_token(T_ARRAY, start_line);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 59 "decaf.l"
{ return make_token(yytext[0], current_line); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 61 "decaf.l"
{return make_token(T_BOOLLITERAL, current_line, yytext); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 62 "decaf.l"
{return make_token(T_BOOLLITERAL, current_line, yytext); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 63 "decaf.l"
{ string_content = yytext;
              if (string_content.length() > 31)
                  lex_error("Identifier %s too long", yytext);
              else
                  return make_token(T_IDENTIFIER, current_line, yytext);}
	YY_BREAK
case 37:
/* rule 37 can match eol */
YY_RULE_SETUP
#line 68 "decaf.l"
{ string_content = yytext;
                        if (string_content == "void")
                            return make_token(T_VOID, current_line);
                        if (string_content == "int")
                            return make_token(T_INT, current_line);
                        if (string_content == "true" || string_content == "false")
                            return make_token(T_BOOLLITERAL, current_line, yytext);
                        if (string_content == "double")
                            return make_token(T_DOUBLE, current_line);
                        if (string_content == "bool")
                            return make_token(T_BOOL, current_line);
                        if (string_content == "string")
                            return make_token(T_STRING, current_line, yytext);
                        if (string_content == "class")
                            return make_token(T_CLASS, current_line);
                        if (string_content == "interface")
                            return make_token(T_INTERFACE, current_line);
                        if (string_content == "null")
                            return make_token(T_NULL, current_line);
                        if (string_content == "this")
                            return make_token(T_THIS, current_line);
                        if (string_content == "extends")
                            return make_token(T_EXTENDS, current_line);
                        if (string_content == "implements")
                            return make_token(T_IMPLEMENTS, current_line);
                        if (string_content == "for")
                            return make_token(T_FOR, current_line);
                        if (string_content == "while")
                            return make_token(T_WHILE, current_line);
                        if (string_content == "if")
                            return make_token(T_IF, current_line);
                        if (string_content == "else")
                            return make_token(T_ELSE, current_line);
                        if (string_content == "return")
                            return make_token(T_RETURN, current_line);
                        if (string_content == "break")
                            return make_token(T_BREAK, current_line);
                        if (string_content == "New")
                            return make_token(T_NEW, current_line);
                        if (string_content == "NewArray")
                            return make_token(T_NEWARRAY, current_line);
                        if (string_content == "Print")
                            return make_token(T_PRINT, current_line);
                        if (string_content == "ReadInteger")
                            return make_token(T_READINTEGER, current_line);
                        if (string_content == "ReadLine")
                            return make_token(T_READLINE, current_line);
                        else
                          return make_token(T_TYPEIDENTIFIER, current_line, yytext);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 117 "decaf.l"
{ return make_token(T_DBLLITERAL, current_line, yytext); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 118 "decaf.l"
{ return make_token(T_INTLITERAL, current_line, yytext); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 120 "decaf.l"
{BEGIN(COMMENT);}
	YY_BREAK
case 41:
/* rule 41 can match eol */
YY_RULE_SETUP
#line 121 "decaf.l"
{BEGIN(INITIAL); current_line += 1; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 122 "decaf.l"
{}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 124 "decaf.l"
{ BEGIN(MULTILINECOMMENT);
       start_line = current_line;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 126 "decaf.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP
#line 127 "decaf.l"
{current_line++;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 128 "decaf.l"
{}
	YY_BREAK
case YY_STATE_EOF(MULTILINECOMMENT):
#line 129 "decaf.l"
{lex_error("Unenclosed block comment on line %d", start_line);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 131 "decaf.l"
{ BEGIN(STRING); }
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 132 "decaf.l"
{ lex_error("Missing \" at the end of string literal"); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 133 "decaf.l"
{ BEGIN(INITIAL);
             return make_token(T_STRINGLITERAL, current_line, string_content); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 135 "decaf.l"
{ string_content = yytext; }
	YY_BREAK
case 51:
/* rule 51 can match eol */
YY_RULE_SETUP
#line 137 "decaf.l"
{current_line++;}
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 138 "decaf.l"
{}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 140 "decaf.l"
{lex_error("Unrecognized character");}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 141 "decaf.l"
ECHO;
	YY_BREAK
#line 1483 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(COMMENT):
			case YY_STATE_EOF(STRING):
			case YY_STATE_EOF(ARRAY):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 181 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    
	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 181 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 180);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 141 "decaf.l"



